### ISSUE TITLE
Ask for pretrain model

### ISSUE THREAD

**Issue by 5RJ** [fudan-zvg/SOFT#1]
Dear Jiachen, 
    Thanks for your work! Would you like to share the pretrained models on ImageNet？ Best wishes!

**Comment by lzrobots** [comment]
Hi thanks for your interests. We will provide the trained models and it takes a bit time. in the mean time you are encouraged to train from your end and let us know whatever you got.

**Comment by lzrobots** [comment]
@5RJ we have tiny model uploaded. More is coming
